### ISSUE TITLE
Issue with `/tmp/nri-prelude-logs` file

### ISSUE THREAD

**Issue by ghost** [NoRedInk/haskell-libraries#1]
@Arkham said:

> I saw this failure on Travis:
> 
> TEST RUN PASSED
> 
> Passed:    47
> 
> tests: /tmp/nri-prelude-logs: openFile: permission denied (Permission denied)
> 
> any idea what might have caused this?

**Comment by ghost** [comment]
The problem: Our observability tooling makes it so we log to the `/tmp/nri-prelude-logs` path. Our tests run various bits of instrumented code, and so effectively log there too. This can happen when multiple users try to access that file. I've seen this with my own local user on the OS and the nixbld user of my multi-user nix installation.

Don't know which two users would be conflicting in the case of Travis though. Maybe two different `nixbld` users?

I'm thinking we should maybe prevent local monorepo tests from writing to that file at all.

**Comment by Arkham** [comment]
could we not create the file with 777 permissions as a quick fix? or do you mean that the problem happens when multiple users try to access the same file concurrently?

another idea would be to write the file as `~/.nri-prelude-logs` in the home directory of the user running the command.

**Comment by ghost** [comment]
No, it's not a concurrency problem.

I like creating it with 777 permissions! That makes a lot of sense to me.
