### ISSUE TITLE
Make failing spans easier to access

### ISSUE THREAD

**Issue by jwoudenberg-nri** [NoRedInk/haskell-libraries#32]
Multiple possibilities
- A sorting option that puts failed spans on top
- A filter showing only failing spans
- A hotkey to jump to the next failing span

**Comment by jwoudenberg-nri** [comment]
Implemented filter and search functionality.

**Comment by jwoudenberg-nri** [comment]
@michaelglass @stoeffel

A thought: maybe it'd be nice to have a `-f/--failed` option that starts log-explorer with a pre-filled filter "failed" enabled. Easy access to only failed root spans without needing to change the defaults or adding new functionality/hotkeys. Thoughts?

**Comment by stoeffel** [comment]
I kinda prefer being able to switch between the filters and not having to close the app.
Happy to do `-f` though first to see if that's good enough.

**Comment by stoeffel** [comment]
I was wondering if we should add `m` to access more commands instead of adding more hotkeys.
`m` would open a window/menu with more commands that you could select.

```
_________________
| > failed first |
| > only failed  |
| > quit         |
|________________|

**Comment by jwoudenberg-nri** [comment]
> I kinda prefer being able to switch between the filters and not having to close the app.

I buy this.

> I was wondering if we should add `m` to access more commands instead of adding more hotkeys.

I'm not sure about this. I think there's some good design pressure coming out of trying to keep options simple enough that we can fit all the actions in a single bar at the bottom. Maybe we'll come up with too many great ideas and it just won't work, but I'd love to see how far we can push it.

I think that applies to this particular case. If we have options to search for failed items, an action to show only failed items, and another action to show all items with the failed ones on top. Would we use all of those?
