### ISSUE TITLE
nri-prelude Test Failure on latest Stackage Nightly

### ISSUE THREAD

**Issue by jkachmar** [NoRedInk/haskell-libraries#45]
Please see the following issue for details; it looks as if the `nri-prelude` test suite is failing when run against the latest Stackage Nightly snapshot.

https://github.com/commercialhaskell/stackage/issues/5884

I haven't gotten the chance to reproduce/debug this locally, but if I do I'll try to update this and/or the associated Stackage issue with more information.

**Comment by jwoudenberg-nri** [comment]
This has been fixed!
